<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Solicitar permisos de Administrador al ejecutar (UAC) -->
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ControlLaboratorio.Agent.exe" />
    <EmbeddedResource Include="Resources\wpfgfx_cor3.dll" />
    <EmbeddedResource Include="Resources\PresentationNative_cor3.dll" />
    <EmbeddedResource Include="Resources\PenImc_cor3.dll" />
    <EmbeddedResource Include="Resources\D3DCompiler_47_cor3.dll" />
    <EmbeddedResource Include="Resources\vcruntime140_cor3.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.manifest" />
  </ItemGroup>

</Project>