// <auto-generated />
using System;
using ControlLaboratorio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlLaboratorio.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260617152754_AddUbicacionLibro")]
    partial class AddUbicacionLibro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlLaboratorio.API.Models.Alumno", b =>
                {
                    b.Property<int>("AlumnoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlumnoID"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoUniversitario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("LimiteDiarioSegundos")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AlumnoID");

                    b.HasIndex("CodigoUniversitario")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoID"));

                    b.Property<string>("AgentVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AgentVersionFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PosicionMapa")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EquipoID");

                    b.HasIndex("NombreRed")
                        .IsUnique();

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Favorito", b =>
                {
                    b.Property<int>("FavoritoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoritoID"));

                    b.Property<int>("AlumnoID")
                        .HasColumnType("int");

                    b.Property<int>("LibroID")
                        .HasColumnType("int");

                    b.HasKey("FavoritoID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("LibroID");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Libro", b =>
                {
                    b.Property<int>("LibroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroID"));

                    b.Property<string>("Anio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cara")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Estante")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroClasificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NroRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<int?>("Piso")
                        .HasColumnType("int");

                    b.Property<string>("Portada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LibroID");

                    b.HasIndex("CodigoBarras")
                        .IsUnique();

                    b.HasIndex("NroRegistro")
                        .IsUnique();

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Multa", b =>
                {
                    b.Property<int>("MultaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MultaID"));

                    b.Property<int>("AlumnoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrestamoID")
                        .HasColumnType("int");

                    b.HasKey("MultaID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("PrestamoID");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoID"));

                    b.Property<int>("AlumnoID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibroID")
                        .HasColumnType("int");

                    b.HasKey("PrestamoID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("LibroID");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Sesion", b =>
                {
                    b.Property<int>("SesionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionID"));

                    b.Property<int>("AlumnoID")
                        .HasColumnType("int");

                    b.Property<int>("EquipoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraLimite")
                        .HasColumnType("datetime2");

                    b.HasKey("SesionID");

                    b.HasIndex("AlumnoID");

                    b.HasIndex("EquipoID");

                    b.HasIndex("Fecha");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Favorito", b =>
                {
                    b.HasOne("ControlLaboratorio.API.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlLaboratorio.API.Models.Libro", "Libro")
                        .WithMany("Favoritos")
                        .HasForeignKey("LibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Multa", b =>
                {
                    b.HasOne("ControlLaboratorio.API.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlLaboratorio.API.Models.Prestamo", "Prestamo")
                        .WithMany("Multas")
                        .HasForeignKey("PrestamoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Prestamo", b =>
                {
                    b.HasOne("ControlLaboratorio.API.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlLaboratorio.API.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Sesion", b =>
                {
                    b.HasOne("ControlLaboratorio.API.Models.Alumno", "Alumno")
                        .WithMany("Sesiones")
                        .HasForeignKey("AlumnoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlLaboratorio.API.Models.Equipo", "Equipo")
                        .WithMany("Sesiones")
                        .HasForeignKey("EquipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Alumno", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Equipo", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Libro", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("ControlLaboratorio.API.Models.Prestamo", b =>
                {
                    b.Navigation("Multas");
                });
#pragma warning restore 612, 618
        }
    }
}
